#PASS: (0)
AG(start -> AX AX AF ~busy)
#PASS: (1)
AG(start -> AX AX AX AX AF ~busy)
#PASS: (2)
AG(start -> AF ~busy)
#PASS: (3)
AG(start -> EF ~busy)
#FAIL: (4)
AG(start -> EX EX EX EX EX EX EX EX ~busy)
#PASS: (5)
AG(start -> EX EX EX EX EX EX EX EX EX EX EX EX EX EX EX EX EX busy)
