#PASS: (0-2)
AG(turn & winning -> lose | AX((turn == winning) & AF lose))
AG(turn & winning & ~lose -> AX((turn == winning) & ~lose))
AG(turn & winning -> AX((turn == winning) & ~lose))
#FAIL: (3-4)
AG(~turn & ~winning & ~lose -> AX((turn == winning) & ~lose))
AG(turn == winning -> AF lose)
#PASS: (5-6)
AG AF(win | lose)
AG(turn & winning -> AF(win | lose))
#FAIL: (7-8)
AG(lose -> AG lose)
AG(lose -> AG ~win)
