#FAIL: (0)
AG(Busy -> AF ~Busy)
#PASS: (1)
AG(Busy -> EF ~Busy)
#PASS: (2)
AG(WCtrlDataStart -> AF Busy)
#PASS: (3)
AG(WCtrlDataStart -> EF MdoEn)
#PASS: (4)
AG(RStatStart -> AF Busy)
#PASS: (5)
AG(RStatStart -> EF MdoEn)
#PASS: (6)
AG(MdoEn -> Busy)
#FAIL: (7)
AG(Busy -> MdoEn)
#PASS: (8)
AG(EndBusy -> EX ~Busy)
#PASS: (9)
AG(EndBusy -> EX ~EndBusy)
#FAIL: (10)
AG(SyncStatMdcEn | AF ~Busy)
