#FAIL: (0)
AG(Busy -> AF ~Busy)
#PASS: (1)
AG(Busy -> EF ~Busy)
#PASS: (2)
AG(WCtrlDataStart -> AX Busy)
#PASS: (3)
AG(WCtrlDataStart -> AX MdoEn)
#PASS: (4)
AG(RStatStart -> AX Busy)
#PASS: (5)
AG(RStatStart -> AX MdoEn)
#PASS: (6)
AG(MdoEn -> Busy)
#FAIL: (7)
AG(Busy -> MdoEn)
#PASS: (8)
AG(EndBusy -> AX ~Busy)
#PASS: (9)
AG(EndBusy -> AX ~EndBusy)
#FAIL: (10)
AG(SyncStatMdcEn | AF ~Busy)
